name: Run Python script

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Make setup script executable
      run: chmod +x ./setup.sh

    - name: Run setup script
      run: source setup.sh

    - name: Log in to Hugging Face
      run: uv run hf_login.py

    - name: Deploy to Spaces
      run: gradio deploy
